en:
  languageName: English
  weight: 1
  params:
    ### copyright (markdown can be used) ###
    copyright: "Copyright &copy; {{< current_year >}} DeepCausality. All rights reserved. The DeepCausality Authors. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) by [CNCF](https://www.cncf.io)."
    title: "DeepCausality"
    description: "Computational causality for Rust"

    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/accessibility/"

    ### calls to action ###
    main_cta:
      text: "Getting Started"
      link: "/getting-started/"

    footer_cta:
      text: "GitHub"
      link: "https://github.com/deepcausality-rs/deep_causality"

    github_edit: "Edit this page on GitHub"

  ### menu ###
  menu:
    main:
    - identifier: "about"
      post: "About DeepCausality"
      name: "About"
      url: "/about/"
      weight: 1

    - identifier: "docs"
      name: "Documentation"
      url: "/docs/"
      weight: 2

    - identifier: "Intro"
      name: "Introduction"
      url: "/docs/intro/"
      weight: 1
      parent: "docs"

    - identifier: "architecture"
      name: "Architecture"
      url: "/docs/architecture/"
      weight: 2
      parent: "docs"

    - identifier: "background"
      name: "Background"
      url: "/docs/background/"
      weight: 3
      parent: "docs"

    - identifier: "concepts"
      name: "Concepts"
      url: "/docs/concepts/"
      weight: 4
      parent: "docs"

    - identifier: "faq"
      name: "FAQ"
      url: "/faq/"
      weight: 5
      parent: "docs"

    - identifier: "Limitations"
      name: "Limitations"
      url: "/docs/limitations/"
      weight: 6
      parent: "docs"

    - identifier: "why"
      name: "Why?"
      url: "/docs/why/"
      weight: 7
      parent: "docs"

    - identifier: "community"
      name: "Community"
      url: "/community/"
      weight: 4

    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 6

    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 7
